/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jemfjptdpxocatjhjolo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbWZqcHRkcHhvY2F0amhqb2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjQ2MzEsImV4cCI6MjA3MzAwMDYzMX0.vv13OAGMJtgx_LlrbBraae-9cpBQrvTN8cPJDRMu9GA"
